# Generated by Django 5.2.5 on 2025-09-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='acceess_token',
            new_name='access_token',
        ),
    ]
